<?php
/**
 * Textos de usuario del checklist SEO México.
 * description = de qué va | correction = qué se corrigió / qué se logra
 * plan = calendario de ejecución para pendientes (start/due/effort/can_start_now)
 * execution = code (sitio/admin/AutoFix) | external (GSC, GBP, ops, contenido humano)
 *
 * @return list<array<string,mixed>>
 */
function cw_seo_mexico_checklist_catalog_items(): array
{
    return [
        // 1 Fundamentos
        ['key' => 'plazas_prioridad', 'phase' => '01_fundamentos', 'sort' => 10,
            'execution' => 'code',
            'title' => 'Definir lista de 8–12 plazas prioritarias',
            'description' => 'Elegir las ciudades donde ConlineWeb va a concentrar SEO los próximos 90 días (no intentar atacar todo México a la vez).',
            'correction' => 'Quedaron fijadas 10 plazas prioritarias: CDMX, Guadalajara, Monterrey, León, Querétaro, Puebla, Mérida, Tijuana, Cancún y Toluca, con vigencia de 90 días.'],
        ['key' => 'gsc_baseline', 'phase' => '01_fundamentos', 'sort' => 20,
            'execution' => 'external',
            'title' => 'Baseline en Google Search Console',
            'description' => 'Sacar una foto inicial de cómo nos encuentra Google hoy en las páginas de México (impresiones, clics y URLs que ya aparecen).',
            'correction' => 'Cuando se complete: tendrás un punto de partida medible en GSC para comparar mes a mes si las plazas prioritarias mejoran.',
            'plan' => [
                'can_start_now' => true,
                'start' => '2026-07-18',
                'due' => '2026-07-21',
                'effort' => '4–6 horas',
                'window' => 'Esta semana',
                'note' => 'Se puede hacer ya: exportar impresiones, clics y URLs /mexico/ en GSC y guardar el baseline (screenshot + CSV).',
            ]],
        ['key' => 'analytics_leads_geo', 'phase' => '01_fundamentos', 'sort' => 30,
            'execution' => 'external',
            'title' => 'Cruzar leads reales vs plazas',
            'description' => 'Revisar de qué ciudades ya llegan WhatsApp o formularios, para no invertir SEO donde no hay demanda real.',
            'correction' => 'Cuando se complete: la lista de plazas priorizadas coincidirá con donde ya hay leads o potencial comercial comprobado.',
            'plan' => [
                'can_start_now' => true,
                'start' => '2026-07-18',
                'due' => '2026-07-23',
                'effort' => '1 día',
                'window' => 'Esta semana',
                'note' => 'Se puede hacer ya con paneles Plazas/URLs + modal de leads: cruzar contactos reales vs las 10 plazas y anotar hallazgos.',
            ]],
        ['key' => 'kpi_90d', 'phase' => '01_fundamentos', 'sort' => 40,
            'execution' => 'code',
            'title' => 'Definir KPIs de 90 días',
            'description' => 'Acordar metas claras a 3 meses (por ejemplo más clics orgánicos y más leads desde plazas prioritarias).',
            'correction' => 'Quedó el panel Plazas 90d (Analytics) con KPIs en vivo: visitas, sesiones, leads, calificados, cerrados, tasa lead, visitantes locales y semáforo. Metas: ≥5 plazas con tráfico, ≥3 con leads, ≥8 leads geo y ≥25% calificados. GSC se revisa aparte.'],

        // 2 Contenido
        ['key' => 'rewrite_hubs_plazas', 'phase' => '02_contenido', 'sort' => 10,
            'execution' => 'code',
            'title' => 'Reescribir hubs de plazas prioritarias',
            'description' => 'Cada ciudad prioritaria debe tener una página propia con texto único (mercado local, oferta, preguntas frecuentes y llamada a cotizar), no un texto genérico copiado.',
            'correction' => 'Se publicó contenido único en los hubs de las 10 plazas prioritarias (título, descripción, hero, cuerpo y FAQs orientados a cada ciudad).'],
        ['key' => 'rewrite_servicio_geo', 'phase' => '02_contenido', 'sort' => 20,
            'execution' => 'code',
            'title' => 'Reforzar páginas servicio × plaza (top 5 servicios)',
            'description' => 'Además del hub de ciudad, cada plaza top necesita páginas claras por servicio (web, software, tienda, SEO e IA) para quien busca ese servicio en esa ciudad.',
            'correction' => 'Se reforzaron 50 páginas (10 plazas × 5 servicios) con contenido propio servicio×ciudad, listas para indexar y cotizar.'],
        ['key' => 'casos_locales', 'phase' => '02_contenido', 'sort' => 30,
            'execution' => 'external',
            'title' => 'Publicar al menos 1 caso/prueba por plaza top',
            'description' => 'En la página de cada ciudad prioritaria debe verse al menos un proyecto o evidencia real de esa zona, para generar confianza y SEO local.',
            'correction' => 'Parcial: ya hay casos reales en CDMX, León, Monterrey y Guadalajara (y Aguascalientes extra). Aún faltan casos en Querétaro, Puebla, Mérida, Tijuana, Cancún y Toluca.',
            'plan' => [
                'can_start_now' => true,
                'start' => '2026-07-18',
                'due' => '2026-08-15',
                'effort' => '2–3 semanas (6 plazas)',
                'window' => 'Jul–Ago 2026',
                'note' => 'Trabajar ya: 1–2 casos/semana (Querétaro, Puebla, Mérida, Tijuana, Cancún, Toluca). Solo evidencia real; no inventar casos.',
            ]],
        ['key' => 'blog_internlink', 'phase' => '02_contenido', 'sort' => 40,
            'execution' => 'code',
            'title' => 'Enlazar blog ↔ páginas geo prioritarias',
            'description' => 'Conectar artículos del blog con las páginas de ciudad (y al revés) para que Google y el visitante pasen de la guía al hub local.',
            'correction' => 'Cada plaza prioritaria enlaza guías del blog, y el artículo de SEO local enlaza las 10 ciudades; además hay bloque de cobertura local en artículos clave.'],

        // 3 Técnico
        ['key' => 'sitemap_completo', 'phase' => '03_tecnico', 'sort' => 10,
            'execution' => 'code',
            'title' => 'Sitemap México completo',
            'description' => 'Decirle a Google, con un mapa de sitio ordenado, cuáles URLs de México y del blog debe rastrear (sin duplicados cortos).',
            'correction' => 'Quedó el sitemap México con URLs canónicas (hub, servicios y geo), el sitemap del blog, y el índice que debes dar de alta en GSC: https://conlineweb.com/sitemap-index.xml'],
        ['key' => 'canibalizacion', 'phase' => '03_tecnico', 'sort' => 20,
            'execution' => 'code',
            'title' => 'Revisar canibalización de keywords',
            'description' => 'Evitar que varias URLs peleen por la misma búsqueda (por ejemplo ruta corta y ruta larga de la misma ciudad).',
            'correction' => 'Las rutas cortas redirigen 301 a la URL canónica; el sitemap y el directorio interno ya no promocionan duplicados; nacional vs local y ciudad vs estado quedan diferenciados. '
                . 'Excepción planificada: fases short_urls_fase1–4 indexan cortas comerciales con contenido único (ver tareas Fase 1–4).'],
        ['key' => 'short_urls_fase1', 'phase' => '03_tecnico', 'sort' => 25,
            'execution' => 'code',
            'title' => 'Fase 1 — URLs cortas comerciales (50 URLs piloto)',
            'description' => 'Indexar landings comerciales en /mexico/{plaza}/servicios/{svc}/ para 10 plazas prioritarias × 5 servicios. '
                . 'Contenido único vs hub largo; objetivo sitemap ~1 252 URLs (+50). La IA encola propuestas automáticamente.',
            'correction' => 'Pendiente: aplicar propuestas short_url_commercial hasta 50/50. Cada URL con H1 comercial, FAQ local, canonical propia y enlace al hub largo.',
            'plan' => [
                'can_start_now' => true,
                'start' => '2026-07-22',
                'due' => '2026-08-31',
                'effort' => '4–6 semanas',
                'window' => '22 jul – 31 ago 2026',
                'note' => 'Plazas: CDMX, Guadalajara, Monterrey, León, Querétaro, Puebla, Mérida, Tijuana, Cancún, Toluca. '
                    . 'Cron IA genera propuestas en cola; aprobar en pestaña Propuestas. No publicar duplicados 301.',
            ]],
        ['key' => 'short_urls_fase2', 'phase' => '03_tecnico', 'sort' => 26,
            'execution' => 'code',
            'title' => 'Fase 2 — Expansión ciudades (+45 URLs cortas)',
            'description' => '9 ciudades restantes en locations.php × 5 servicios. Mismo modelo comercial. Objetivo sitemap ~1 297 URLs.',
            'correction' => 'Pendiente: tras revisión GSC 30 d post-Fase 1. IA encola propuestas al iniciar ventana 01-sep-2026.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-09-01',
                'due' => '2026-10-15',
                'effort' => '8–12 semanas',
                'window' => '1 sep – 15 oct 2026',
                'note' => 'Requisito: Fase 1 ≥90% aplicada + revisión GSC canibalización. Ciudades no prioritarias.',
            ]],
        ['key' => 'short_urls_fase3', 'phase' => '03_tecnico', 'sort' => 27,
            'execution' => 'code',
            'title' => 'Fase 3 — Estados (+160 URLs cortas)',
            'description' => '32 estados × 5 servicios con intención estatal («Desarrollo web en Jalisco»). Objetivo sitemap ~1 457 URLs.',
            'correction' => 'Pendiente: ventana 16-oct-2026. Diferenciar homónimos ciudad/estado.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-10-16',
                'due' => '2026-12-15',
                'effort' => '12–16 semanas',
                'window' => '16 oct – 15 dic 2026',
                'note' => 'Requisito: Fase 2 ≥90% + GSC estable. Intención cobertura estatal, no copiar textos de ciudad.',
            ]],
        ['key' => 'short_urls_fase4', 'phase' => '03_tecnico', 'sort' => 28,
            'execution' => 'code',
            'title' => 'Fase 4 — Hubs cortos opcionales (+45 URLs)',
            'description' => 'Landings /mexico/{plaza}/ generales solo si Fases 1–3 no canibalizan. Objetivo sitemap ~1 502 URLs.',
            'correction' => 'Opcional — pendiente ventana 16-dic-2026. Solo activar con luz verde GSC.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-12-16',
                'due' => '2027-01-31',
                'effort' => '4–6 semanas',
                'window' => '16 dic 2026 – 31 ene 2027',
                'note' => 'Opcional. ~45 hubs cortos. No duplicar hub largo palabra por palabra.',
            ]],
        ['key' => 'cwv_mobile', 'phase' => '03_tecnico', 'sort' => 30,
            'execution' => 'code',
            'title' => 'Validar Core Web Vitals móvil en landings geo',
            'description' => 'Revisar que las landings de ciudad carguen bien en celular (velocidad y estabilidad), priorizando las plazas top, sin romper el diseño.',
            'correction' => 'Se aplicaron mejoras técnicas seguras (carga de menú/SweetAlert, logos con tamaño, fuentes, CSS). Desktop León ~95; móvil aún se revalida en PSI porque el hero animado limita el score sin tocar diseño.'],

        // 4 Autoridad
        ['key' => 'gbp_activo', 'phase' => '04_autoridad', 'sort' => 10,
            'execution' => 'external',
            'title' => 'Google Business Profile activo y completo',
            'description' => 'Tener la ficha de Google (Maps) completa y viva: categorías, servicios, fotos, horarios y publicaciones.',
            'correction' => 'Cuando se complete: la ficha de Google estará lista para captar búsquedas locales y respaldar el SEO de las plazas.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-07-22',
                'due' => '2026-08-01',
                'effort' => '1 semana',
                'window' => 'Fin de julio',
                'note' => 'Plazo estimado: requiere acceso al Google Business Profile. Completar categorías, servicios, fotos, horarios y 1–2 posts.',
            ]],
        ['key' => 'reseñas_ritmo', 'phase' => '04_autoridad', 'sort' => 20,
            'execution' => 'external',
            'title' => 'Ritmo de reseñas (meta mensual)',
            'description' => 'Definir cuántas reseñas nuevas reales se buscan al mes y llevar un ritmo constante (sin comprar reseñas).',
            'correction' => 'Cuando se complete: habrá una meta mensual clara y un proceso para pedir reseñas después de entregas exitosas.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-08-01',
                'due' => '2026-08-15',
                'effort' => '3–5 días (setup) + mensual',
                'window' => 'Agosto 2026',
                'note' => 'Después de GBP. Definir meta (ej. 4–8/mes) y proceso post-entrega; no se puede forzar sin clientes/respuestas reales.',
            ]],
        ['key' => 'citaciones_enlaces', 'phase' => '04_autoridad', 'sort' => 30,
            'execution' => 'external',
            'title' => 'Primer bloque de citaciones / enlaces',
            'description' => 'Conseguir menciones o enlaces serios (directorios, partners, notas) que apunten a conlineweb.com y den autoridad.',
            'correction' => 'Cuando se complete: existirá un primer paquete de enlaces/citaciones de calidad hacia el sitio.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-08-04',
                'due' => '2026-08-29',
                'effort' => '3–4 semanas',
                'window' => 'Agosto 2026',
                'note' => 'Outreach externo (directorios, partners, notas). Meta: primer bloque de 8–15 citaciones/enlaces de calidad.',
            ]],
        ['key' => 'marca_consistente', 'phase' => '04_autoridad', 'sort' => 40,
            'execution' => 'code',
            'title' => 'NAP / marca consistente',
            'description' => 'Que el nombre, teléfono y sitio web sean iguales en conlineweb.com (footer, schema, contacto y landings México), listos para alinear después con Google Business y perfiles públicos.',
            'correction' => 'Quedó fuente única includes/cw-nap.php: ConlineWeb · Ana María 104, Col. Loma Bonita, CP 37420, León, Guanajuato · +52 477 118 1285 / +52 812 009 4766 · info@conlineweb.com · https://conlineweb.com. Footer, schema home, SEO meta, page-factory México, contacto y legal ya la consumen. GBP/directorios externos se alinean cuando haya acceso a la ficha.',
            'plan' => [
                'can_start_now' => true,
                'start' => '2026-07-18',
                'due' => '2026-07-18',
                'effort' => 'Hecho en sitio web',
                'window' => 'Completado',
                'note' => 'Sitio público unificado. Pendiente externo: copiar la misma NAP a Google Business Profile y citaciones.',
            ]],

        // 5 Medición
        ['key' => 'panel_gsc_mensual', 'phase' => '05_medicion', 'sort' => 10,
            'execution' => 'external',
            'title' => 'Revisión mensual GSC por plaza',
            'description' => 'Cada mes revisar por ciudad: impresiones → clics → leads, y pausar plazas que no muevan la aguja tras 90 días.',
            'correction' => 'Cuando se complete: habrá un hábito mensual de revisión por plaza con criterios de seguir o pausar.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-08-18',
                'due' => '2026-08-22',
                'effort' => '2–3 horas / mes',
                'window' => 'Mensual desde ago',
                'note' => 'Primera revisión ~30 días después del baseline GSC; luego cada mes (impresiones → clics → leads por plaza).',
            ]],
        ['key' => 'ciudades_faltantes', 'phase' => '05_medicion', 'sort' => 20,
            'execution' => 'external',
            'title' => 'Agregar ciudades faltantes solo con contenido propio',
            'description' => 'Solo abrir nuevas ciudades cuando haya contenido y plan real; no crear páginas vacías “por si acaso”.',
            'correction' => 'Cuando se complete: el mapa de cobertura crecerá con calidad, no con URLs huecas.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-09-15',
                'due' => '2026-10-15',
                'effort' => '2–4 semanas (según demanda)',
                'window' => 'Sep–Oct 2026',
                'note' => 'No abrir ahora. Esperar revisión a 60–90 días; solo nuevas ciudades con contenido propio y plan comercial.',
            ]],
        ['key' => 'escala_nacional', 'phase' => '05_medicion', 'sort' => 30,
            'execution' => 'external',
            'title' => 'Ataque a keywords nacionales medianas',
            'description' => 'Cuando ya haya fuerza local, competir también por búsquedas nacionales o regionales de segundo nivel (no solo ciudad).',
            'correction' => 'Cuando se complete: además del SEO local, habrá una estrategia para keywords nacionales medianas con chance real.',
            'plan' => [
                'can_start_now' => false,
                'start' => '2026-10-01',
                'due' => '2026-10-31',
                'effort' => '3–4 semanas',
                'window' => 'Octubre 2026',
                'note' => 'Fase final del plan 90 días: solo cuando haya señales locales. Keywords nacionales/regionales medianas con chance real.',
            ]],
    ];
}
